/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as PlantaoRouteImport } from './routes/plantao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnviarPautaRouteImport } from './routes/enviar-pauta'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiaSlugRouteImport } from './routes/noticia.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminPushRouteImport } from './routes/_authenticated/admin.push'
import { Route as AuthenticatedAdminPostSocialRouteImport } from './routes/_authenticated/admin.post-social'
import { Route as AuthenticatedAdminPautasRouteImport } from './routes/_authenticated/admin.pautas'
import { Route as AuthenticatedAdminNoticiasRouteImport } from './routes/_authenticated/admin.noticias'
import { Route as AuthenticatedAdminGeradorSocialRouteImport } from './routes/_authenticated/admin.gerador-social'
import { Route as AuthenticatedAdminFontesRouteImport } from './routes/_authenticated/admin.fontes'
import { Route as AuthenticatedAdminFilaIaRouteImport } from './routes/_authenticated/admin.fila-ia'
import { Route as AuthenticatedAdminCriarRouteImport } from './routes/_authenticated/admin.criar'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin.config'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminAnunciosRouteImport } from './routes/_authenticated/admin.anuncios'
import { Route as ApiPublicHooksFetchRssRouteImport } from './routes/api/public/hooks/fetch-rss'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantaoRoute = PlantaoRouteImport.update({
  id: '/plantao',
  path: '/plantao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviarPautaRoute = EnviarPautaRouteImport.update({
  id: '/enviar-pauta',
  path: '/enviar-pauta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiaSlugRoute = NoticiaSlugRouteImport.update({
  id: '/noticia/$slug',
  path: '/noticia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPushRoute = AuthenticatedAdminPushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPostSocialRoute =
  AuthenticatedAdminPostSocialRouteImport.update({
    id: '/post-social',
    path: '/post-social',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPautasRoute =
  AuthenticatedAdminPautasRouteImport.update({
    id: '/pautas',
    path: '/pautas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNoticiasRoute =
  AuthenticatedAdminNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGeradorSocialRoute =
  AuthenticatedAdminGeradorSocialRouteImport.update({
    id: '/gerador-social',
    path: '/gerador-social',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFontesRoute =
  AuthenticatedAdminFontesRouteImport.update({
    id: '/fontes',
    path: '/fontes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFilaIaRoute =
  AuthenticatedAdminFilaIaRouteImport.update({
    id: '/fila-ia',
    path: '/fila-ia',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCriarRoute = AuthenticatedAdminCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnunciosRoute =
  AuthenticatedAdminAnunciosRouteImport.update({
    id: '/anuncios',
    path: '/anuncios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksFetchRssRoute = ApiPublicHooksFetchRssRouteImport.update({
  id: '/api/public/hooks/fetch-rss',
  path: '/api/public/hooks/fetch-rss',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enviar-pauta': typeof EnviarPautaRoute
  '/login': typeof LoginRoute
  '/plantao': typeof PlantaoRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/criar': typeof AuthenticatedAdminCriarRoute
  '/admin/fila-ia': typeof AuthenticatedAdminFilaIaRoute
  '/admin/fontes': typeof AuthenticatedAdminFontesRoute
  '/admin/gerador-social': typeof AuthenticatedAdminGeradorSocialRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/pautas': typeof AuthenticatedAdminPautasRoute
  '/admin/post-social': typeof AuthenticatedAdminPostSocialRoute
  '/admin/push': typeof AuthenticatedAdminPushRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/fetch-rss': typeof ApiPublicHooksFetchRssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enviar-pauta': typeof EnviarPautaRoute
  '/login': typeof LoginRoute
  '/plantao': typeof PlantaoRoute
  '/videos': typeof VideosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/config': typeof AuthenticatedAdminConfigRoute
  '/admin/criar': typeof AuthenticatedAdminCriarRoute
  '/admin/fila-ia': typeof AuthenticatedAdminFilaIaRoute
  '/admin/fontes': typeof AuthenticatedAdminFontesRoute
  '/admin/gerador-social': typeof AuthenticatedAdminGeradorSocialRoute
  '/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/admin/pautas': typeof AuthenticatedAdminPautasRoute
  '/admin/post-social': typeof AuthenticatedAdminPostSocialRoute
  '/admin/push': typeof AuthenticatedAdminPushRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/fetch-rss': typeof ApiPublicHooksFetchRssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/enviar-pauta': typeof EnviarPautaRoute
  '/login': typeof LoginRoute
  '/plantao': typeof PlantaoRoute
  '/videos': typeof VideosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/noticia/$slug': typeof NoticiaSlugRoute
  '/_authenticated/admin/anuncios': typeof AuthenticatedAdminAnunciosRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/config': typeof AuthenticatedAdminConfigRoute
  '/_authenticated/admin/criar': typeof AuthenticatedAdminCriarRoute
  '/_authenticated/admin/fila-ia': typeof AuthenticatedAdminFilaIaRoute
  '/_authenticated/admin/fontes': typeof AuthenticatedAdminFontesRoute
  '/_authenticated/admin/gerador-social': typeof AuthenticatedAdminGeradorSocialRoute
  '/_authenticated/admin/noticias': typeof AuthenticatedAdminNoticiasRoute
  '/_authenticated/admin/pautas': typeof AuthenticatedAdminPautasRoute
  '/_authenticated/admin/post-social': typeof AuthenticatedAdminPostSocialRoute
  '/_authenticated/admin/push': typeof AuthenticatedAdminPushRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/fetch-rss': typeof ApiPublicHooksFetchRssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/enviar-pauta'
    | '/login'
    | '/plantao'
    | '/videos'
    | '/admin'
    | '/categoria/$slug'
    | '/noticia/$slug'
    | '/admin/anuncios'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/criar'
    | '/admin/fila-ia'
    | '/admin/fontes'
    | '/admin/gerador-social'
    | '/admin/noticias'
    | '/admin/pautas'
    | '/admin/post-social'
    | '/admin/push'
    | '/admin/usuarios'
    | '/admin/'
    | '/api/public/hooks/fetch-rss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/enviar-pauta'
    | '/login'
    | '/plantao'
    | '/videos'
    | '/categoria/$slug'
    | '/noticia/$slug'
    | '/admin/anuncios'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/criar'
    | '/admin/fila-ia'
    | '/admin/fontes'
    | '/admin/gerador-social'
    | '/admin/noticias'
    | '/admin/pautas'
    | '/admin/post-social'
    | '/admin/push'
    | '/admin/usuarios'
    | '/admin'
    | '/api/public/hooks/fetch-rss'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/enviar-pauta'
    | '/login'
    | '/plantao'
    | '/videos'
    | '/_authenticated/admin'
    | '/categoria/$slug'
    | '/noticia/$slug'
    | '/_authenticated/admin/anuncios'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/config'
    | '/_authenticated/admin/criar'
    | '/_authenticated/admin/fila-ia'
    | '/_authenticated/admin/fontes'
    | '/_authenticated/admin/gerador-social'
    | '/_authenticated/admin/noticias'
    | '/_authenticated/admin/pautas'
    | '/_authenticated/admin/post-social'
    | '/_authenticated/admin/push'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/api/public/hooks/fetch-rss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EnviarPautaRoute: typeof EnviarPautaRoute
  LoginRoute: typeof LoginRoute
  PlantaoRoute: typeof PlantaoRoute
  VideosRoute: typeof VideosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  NoticiaSlugRoute: typeof NoticiaSlugRoute
  ApiPublicHooksFetchRssRoute: typeof ApiPublicHooksFetchRssRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantao': {
      id: '/plantao'
      path: '/plantao'
      fullPath: '/plantao'
      preLoaderRoute: typeof PlantaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enviar-pauta': {
      id: '/enviar-pauta'
      path: '/enviar-pauta'
      fullPath: '/enviar-pauta'
      preLoaderRoute: typeof EnviarPautaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticia/$slug': {
      id: '/noticia/$slug'
      path: '/noticia/$slug'
      fullPath: '/noticia/$slug'
      preLoaderRoute: typeof NoticiaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/push': {
      id: '/_authenticated/admin/push'
      path: '/push'
      fullPath: '/admin/push'
      preLoaderRoute: typeof AuthenticatedAdminPushRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/post-social': {
      id: '/_authenticated/admin/post-social'
      path: '/post-social'
      fullPath: '/admin/post-social'
      preLoaderRoute: typeof AuthenticatedAdminPostSocialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pautas': {
      id: '/_authenticated/admin/pautas'
      path: '/pautas'
      fullPath: '/admin/pautas'
      preLoaderRoute: typeof AuthenticatedAdminPautasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/noticias': {
      id: '/_authenticated/admin/noticias'
      path: '/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AuthenticatedAdminNoticiasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gerador-social': {
      id: '/_authenticated/admin/gerador-social'
      path: '/gerador-social'
      fullPath: '/admin/gerador-social'
      preLoaderRoute: typeof AuthenticatedAdminGeradorSocialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fontes': {
      id: '/_authenticated/admin/fontes'
      path: '/fontes'
      fullPath: '/admin/fontes'
      preLoaderRoute: typeof AuthenticatedAdminFontesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fila-ia': {
      id: '/_authenticated/admin/fila-ia'
      path: '/fila-ia'
      fullPath: '/admin/fila-ia'
      preLoaderRoute: typeof AuthenticatedAdminFilaIaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/criar': {
      id: '/_authenticated/admin/criar'
      path: '/criar'
      fullPath: '/admin/criar'
      preLoaderRoute: typeof AuthenticatedAdminCriarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/config': {
      id: '/_authenticated/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/anuncios': {
      id: '/_authenticated/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AuthenticatedAdminAnunciosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/fetch-rss': {
      id: '/api/public/hooks/fetch-rss'
      path: '/api/public/hooks/fetch-rss'
      fullPath: '/api/public/hooks/fetch-rss'
      preLoaderRoute: typeof ApiPublicHooksFetchRssRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnunciosRoute: typeof AuthenticatedAdminAnunciosRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
  AuthenticatedAdminCriarRoute: typeof AuthenticatedAdminCriarRoute
  AuthenticatedAdminFilaIaRoute: typeof AuthenticatedAdminFilaIaRoute
  AuthenticatedAdminFontesRoute: typeof AuthenticatedAdminFontesRoute
  AuthenticatedAdminGeradorSocialRoute: typeof AuthenticatedAdminGeradorSocialRoute
  AuthenticatedAdminNoticiasRoute: typeof AuthenticatedAdminNoticiasRoute
  AuthenticatedAdminPautasRoute: typeof AuthenticatedAdminPautasRoute
  AuthenticatedAdminPostSocialRoute: typeof AuthenticatedAdminPostSocialRoute
  AuthenticatedAdminPushRoute: typeof AuthenticatedAdminPushRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnunciosRoute: AuthenticatedAdminAnunciosRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
  AuthenticatedAdminCriarRoute: AuthenticatedAdminCriarRoute,
  AuthenticatedAdminFilaIaRoute: AuthenticatedAdminFilaIaRoute,
  AuthenticatedAdminFontesRoute: AuthenticatedAdminFontesRoute,
  AuthenticatedAdminGeradorSocialRoute: AuthenticatedAdminGeradorSocialRoute,
  AuthenticatedAdminNoticiasRoute: AuthenticatedAdminNoticiasRoute,
  AuthenticatedAdminPautasRoute: AuthenticatedAdminPautasRoute,
  AuthenticatedAdminPostSocialRoute: AuthenticatedAdminPostSocialRoute,
  AuthenticatedAdminPushRoute: AuthenticatedAdminPushRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EnviarPautaRoute: EnviarPautaRoute,
  LoginRoute: LoginRoute,
  PlantaoRoute: PlantaoRoute,
  VideosRoute: VideosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  NoticiaSlugRoute: NoticiaSlugRoute,
  ApiPublicHooksFetchRssRoute: ApiPublicHooksFetchRssRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
